### ISSUE TITLE
Can't get Chart printed. & Index error when try to Get song on chart by index

### ISSUE THREAD

**Issue by manishmishra15** [guoguo12/billboard-charts#60]
1) Tried running below code and print(chart) gave me nothing but Header "hot-100 chart (current)"
2) printing Song by fetching chart[0] gave me index issue. 

import billboard
chart = billboard.ChartData('hot-100')
print(chart)
song = chart[0]
print(song)

*************Console output 
Traceback (most recent call last):
hot-100 chart (current)
-----------------------
  File "C:/Users/manish/PycharmProjects/SongCollector/POCtest/bilboardLis.py", line 4, in <module>
    song = chart[0]
  File "C:\Users\manish\PycharmProjects\SongCollector\venv\lib\site-packages\billboard.py", line 175, in __getitem__
    return self.entries[key]
IndexError: list index out of range

Process finished with exit code 1

**Comment by manishmishra15** [comment]
Note: requests 2.22.0 & beautifulsoup4 4.8.0 packages are already installed.

**Comment by guoguo12** [comment]
I think they've updated their website recently. We'll need to fix the
library.

**Comment by guoguo12** [comment]
This should be fixed in 5.3.0.

**Comment by manishmishra15** [comment]
I upgraded to 5.3 and it is working now.
