### ISSUE TITLE
Cannot fetch the Hot 100 chart

### ISSUE THREAD

**Issue by marco97pa** [guoguo12/billboard-charts#85]
As of today this simple code started to give me an error:
```
import billboard
chart = billboard.ChartData('hot-100')
```

This is the Trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco97pa/.pyenv/versions/3.9.3/lib/python3.9/site-packages/billboard.py", line 190, in __init__
    self.fetchEntries()
  File "/home/marco97pa/.pyenv/versions/3.9.3/lib/python3.9/site-packages/billboard.py", line 487, in fetchEntries
    self._parsePage(soup)
  File "/home/marco97pa/.pyenv/versions/3.9.3/lib/python3.9/site-packages/billboard.py", line 461, in _parsePage
    self._parseNewStylePage(soup)
  File "/home/marco97pa/.pyenv/versions/3.9.3/lib/python3.9/site-packages/billboard.py", line 319, in _parseNewStylePage
    self.previousDate = soup.select_one("#charts")["data-chart-prev-date"]
TypeError: 'NoneType' object is not subscriptable
```

I run this code everyday and yesterday it was working. Maybe there was a change on structure of the website of the chart?

**Comment by guoguo12** [comment]
Looks like Billboard changed their UI.

Version 6.3.0 fixes support for basic charts (like the Hot 100). Artist charts and year-end charts are still broken.

**Comment by guoguo12** [comment]
Just pushed 7.0.0, which fixes artist and year-end charts (but removes some features like `previousDate` and the `charts()` function, since these are hard to implement now).

**Comment by guoguo12** [comment]
Feel free to reopen this if there are still issues.
